#!/bin/bash

make clean all

#./example RMSD_TEST/ORIGINAL_PDBS/ligand3TMN.sdf RMSD_TEST/ORIGINAL_PDBS/conformer3TMN.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1TMN_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/3TMN_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/3TMN_1TMNreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer3TMN_1TMNreference.sdf >>RMSD_OUTPUT 2>&1
#./example RMSD_TEST/ORIGINAL_PDBS/ligand4TMN.sdf RMSD_TEST/ORIGINAL_PDBS/conformer4TMN.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1TMN_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/4TMN_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/4TMN_1TMNreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer4TMN_1TMNreference.sdf >>RMSD_OUTPUT 2>&1
#./example RMSD_TEST/ORIGINAL_PDBS/ligand1THL.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1THL.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1TMN_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1THL_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/1THL_1TMNreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer1THL_1TMNreference.sdf >>RMSD_OUTPUT 2>&1
#./example RMSD_TEST/ORIGINAL_PDBS/ligand1TLP.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1TLP.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1TMN_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1TLP_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/1TLP_1TMNreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer1TLP_1TMNreference.sdf >>RMSD_OUTPUT 2>&1


#./example RMSD_TEST/ORIGINAL_PDBS/ligand4TMN.sdf RMSD_TEST/ORIGINAL_PDBS/conformer4TMN.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/3TMN_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/4TMN_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/4TMN_3TMNreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer4TMN_3TMNreference.sdf >>RMSD_OUTPUT 2>&1
#./example RMSD_TEST/ORIGINAL_PDBS/ligand1THL.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1THL.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/3TMN_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1THL_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/1THL_3TMNreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer1THL_3TMNreference.sdf >>RMSD_OUTPUT 2>&1
#./example RMSD_TEST/ORIGINAL_PDBS/ligand1TLP.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1TLP.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/3TMN_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1TLP_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/1TLP_3TMNreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer1TLP_3TMNreference.sdf >>RMSD_OUTPUT 2>&1

#./example RMSD_TEST/ORIGINAL_PDBS/ligand1THL.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1THL.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/4TMN_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1THL_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/1THL_4TMNreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer1THL_4TMNreference.sdf >>RMSD_OUTPUT 2>&1
#./example RMSD_TEST/ORIGINAL_PDBS/ligand1TLP.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1TLP.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/4TMN_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1TLP_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/1TLP_4TMNreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer1TLP_4TMNreference.sdf >>RMSD_OUTPUT 2>&1

#./example RMSD_TEST/ORIGINAL_PDBS/ligand1TLP.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1TLP.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1THL_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1TLP_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/1TLP_1THLreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer1TLP_1THLreference.sdf >>RMSD_OUTPUT 2>&1


./example RMSD_TEST/ORIGINAL_PDBS/ligand1TMN.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1TMN.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1TMN_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1TMN_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/1TMN_1TMNreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer1TMN_1TMNreference.sdf >>RMSD_OUTPUT2 2>&1
./example RMSD_TEST/ORIGINAL_PDBS/ligand3TMN.sdf RMSD_TEST/ORIGINAL_PDBS/conformer3TMN.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/3TMN_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/3TMN_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/3TMN_3TMNreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer3TMN_3TMNreference.sdf >>RMSD_OUTPUT2 2>&1
./example RMSD_TEST/ORIGINAL_PDBS/ligand4TMN.sdf RMSD_TEST/ORIGINAL_PDBS/conformer4TMN.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/4TMN_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/4TMN_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/4TMN_4TMNreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer4TMN_4TMNreference.sdf >>RMSD_OUTPUT2 2>&1
./example RMSD_TEST/ORIGINAL_PDBS/ligand1THL.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1THL.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1THL_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1THL_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/1THL_1THLreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer1THL_1THLreference.sdf >>RMSD_OUTPUT2 2>&1
./example RMSD_TEST/ORIGINAL_PDBS/ligand1TLP.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1TLP.sdf  RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1TLP_ligand.sdf RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/1TLP_ligand.sdf RMSD_TEST/ROKS_SUPERPOSITION/1TLP_1TLPreference.sdf RMSD_TEST/ROKS_SUPERPOSITION/conformer1TLP_1TLPreference.sdf >>RMSD_OUTPUT2 2>&1


mv RMSD_OUTPUT2 RMSD_TEST/RMSD_OUTPUT2
git add RMSD_TEST/RMSD_OUTPUT2
git commit -a -m "continuing new conformer sets"

git push
#osascript -e 'tell application "System Events" to sleep'
