#!/bin/bash

make clean all

#./example RMSD_TEST/ORIGINAL_PDBS/ligand1TMN.pdb RMSD_TEST/ORIGINAL_PDBS/ligand1TMN.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1TMN.sdf
#./example RMSD_TEST/ORIGINAL_PDBS/ligand3TMN.pdb RMSD_TEST/ORIGINAL_PDBS/ligand3TMN.sdf RMSD_TEST/ORIGINAL_PDBS/conformer3TMN.sdf
#./example RMSD_TEST/ORIGINAL_PDBS/ligand4TMN.pdb RMSD_TEST/ORIGINAL_PDBS/ligand4TMN.sdf RMSD_TEST/ORIGINAL_PDBS/conformer4TMN.sdf
#./example RMSD_TEST/ORIGINAL_PDBS/ligand1THL.pdb RMSD_TEST/ORIGINAL_PDBS/ligand1THL.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1THL.sdf
#./example RMSD_TEST/ORIGINAL_PDBS/ligand1TLP.pdb RMSD_TEST/ORIGINAL_PDBS/ligand1TLP.sdf RMSD_TEST/ORIGINAL_PDBS/conformer1TLP.sdf


#git add CONFORMERS



for f in `ls RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/`
do
	./example RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/$f RMSD_TEST/1TMN_AS_REFERENCE_IN_CHIMERA_SUPERPOSITION/$f.sdf /dev/null
done


#git commit -a -m "fixing conformer generation performance"
#git push
